packages:
- jaeger-types
- jaeger-opentracing-tags
- jaeger-utils
- monad-jaeger
- monad-logger-jaeger
- jaeger-sampler
- logging-effect-jaeger
- wai-jaeger
- servant-jaeger
- monad-jaeger-metrics-ekg
- monad-jaeger-metrics-prometheus

resolver: lts-9.10

extra-deps:
- lens-properties-4.11
- thrift-0.10.0
- dump-core-0.1.3.1
- monadLib-3.7.3
- prometheus-effect-1.0.0

allow-newer: true
